# -*- coding: utf-8 -*-
"""deteksi detr 300 epoch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDYjmzxjhcn0-r249BMgFrl0g4Sd_hgI

**GPU CHECK**
"""

import torch
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

print("=== GPU CHECK ===")
print("CUDA available :", torch.cuda.is_available())
print("CUDA device cnt:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU name       :", torch.cuda.get_device_name(0))
else:
    print("GPU BELUM AKTIF")
    print("Runtime > Change runtime type > GPU")

!pip install -q torch torchvision
!pip install -q transformers pytorch-lightning
!pip install -q supervision pycocotools coco_eval opencv-python

import torch, transformers, pytorch_lightning
print("Torch       :", torch.__version__)
print("Transformers:", transformers.__version__)
print("Lightning   :", pytorch_lightning.__version__)

"""**LOAD DATASET FROM GOOGLE DRIVE (ZIP)**"""

from google.colab import drive
import zipfile, os, json, random, shutil

drive.mount('/content/drive')

ZIP_PATH = '/content/drive/MyDrive/Data_FracAtlas.zip'
EXTRACT_DIR = '/content'

if not os.path.exists('/content/DataFracAtlas'):
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_DIR)
        print("Dataset extracted")
else:
    print("Dataset already exists")

"""**BUILD COMBINED COCO (fracture + non_fracture)**"""

FRACTURE_JSON = '/content/FracAtlas/Annotations/COCO JSON/COCO_fracture_masks.json'
FRACTURE_IMG_DIR = '/content/FracAtlas/images/Fractured'
NONFRACTURE_IMG_DIR = '/content/FracAtlas/images/Non_fractured'

with open(FRACTURE_JSON) as f:
    coco = json.load(f)

images = coco["images"]
annotations = coco["annotations"]

# only 1 class
categories = [{"id": 1, "name": "fracture"}]

existing_files = {img["file_name"] for img in images}

img_id = max(img["id"] for img in images) + 1

for fname in os.listdir(NONFRACTURE_IMG_DIR):
    if fname in existing_files:
        continue
    images.append({
        "id": img_id,
        "file_name": fname,
        "width": 512,
        "height": 512
    })
    img_id += 1

combined_coco = {
    "images": images,
    "annotations": annotations,
    "categories": categories
}

with open("/content/combined_coco.json", "w") as f:
    json.dump(combined_coco, f)

SRC_JSON = "/content/combined_coco.json"
SRC_IMG = "/content/FracAtlas/images"

import json

with open("/content/Data_FracAtlas/Annotations/COCO JSON/COCO_fracture_masks.json") as f:
    coco = json.load(f)

print("Jumlah citra       :", len(coco["images"]))
print("Jumlah anotasi bbox:", len(coco["annotations"]))
print("Jumlah kelas       :", len(coco["categories"]))
print("Contoh 1 data citra:", coco["images"][0])

"""**SPLIT DATASET COCO (TRAIN / VAL / TEST)**"""

import os
import json
import random
import shutil

SRC_JSON = "/content/Data_FracAtlas/Annotations/COCO JSON/COCO_fracture_masks.json"
SRC_IMG = "/content/Data_FracAtlas/images/Fractured_Image"
OUT_DIR = "/content/dataset_split"

os.makedirs(OUT_DIR, exist_ok=True)

# =======================
# Load COCO annotation
# =======================
with open(SRC_JSON, "r") as f:
    coco = json.load(f)

images = coco["images"]
annotations = coco["annotations"]
categories = coco["categories"]

# =======================
# Shuffle images (copy, not in-place)
# =======================
images_shuffled = images.copy()
random.shuffle(images_shuffled)

N = len(images_shuffled)

splits = {
    "train": images_shuffled[:int(0.7 * N)],
    "val": images_shuffled[int(0.7 * N):int(0.85 * N)],
    "test": images_shuffled[int(0.85 * N):]
}

# =======================
# Helper: find image
# =======================
def find_image(img_dir, filename):
    path = os.path.join(img_dir, filename)
    return path if os.path.exists(path) else None

# =======================
# Create split datasets
# =======================
for split, imgs in splits.items():
    print(f"Processing {split} set...")

    split_dir = os.path.join(OUT_DIR, split)
    img_out_dir = os.path.join(split_dir, "images")
    os.makedirs(img_out_dir, exist_ok=True)

    # Collect image IDs for this split
    img_ids = set(img["id"] for img in imgs)

    # Filter annotations
    anns = [ann for ann in annotations if ann["image_id"] in img_ids]

    # Copy images
    for img in imgs:
        src_path = find_image(SRC_IMG, img["file_name"])
        if src_path:
            shutil.copy(src_path, os.path.join(img_out_dir, img["file_name"]))
        else:
            print("Gambar tidak ditemukan:", img["file_name"])

    # =======================
    # COCO-style output JSON
    # =======================
    out_coco = {
        "images": imgs,
        "annotations": anns,
        "categories": categories
    }

    with open(os.path.join(split_dir, "annotations.json"), "w") as f:
        json.dump(out_coco, f, indent=2)

print("Split dataset COCO selesai!")

import json

def count_data(split):
    # Updated path to match the output directory from the previous cell
    with open(f"/content/dataset_split/{split}/annotations.json") as f:
        coco = json.load(f)
    return len(coco["images"]), len(coco["annotations"])

train_img, train_ann = count_data("train")
val_img, val_ann = count_data("val")
test_img, test_ann = count_data("test")

print("Train :", train_img, "citra,", train_ann, "bbox")
print("Val   :", val_img, "citra,", val_ann, "bbox")
print("Test  :", test_img, "citra,", test_ann, "bbox")

"""**DETR DATASET & DATALOADER**"""

from torchvision.datasets import CocoDetection
from transformers import DetrImageProcessor, DetrForObjectDetection
from torch.utils.data import DataLoader
import pytorch_lightning as pl
import torch

CHECKPOINT = "facebook/detr-resnet-50"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

processor = DetrImageProcessor.from_pretrained(CHECKPOINT)

class CocoDataset(CocoDetection):
    def __init__(self, img_dir, ann_file):
        super().__init__(img_dir, ann_file)

    def __getitem__(self, idx):
        image, target = super().__getitem__(idx)
        image_id = self.ids[idx]
        encoding = processor(
            images=image,
            annotations={"image_id": image_id, "annotations": target},
            return_tensors="pt"
        )
        return encoding["pixel_values"].squeeze(0), encoding["labels"][0]

def collate_fn(batch):
    pixel_values = [b[0] for b in batch]
    labels = [b[1] for b in batch]
    enc = processor.pad(pixel_values, return_tensors="pt")
    return {"pixel_values": enc["pixel_values"], "pixel_mask": enc["pixel_mask"], "labels": labels}

# Correcting the paths to match where the dataset was actually saved
train_ds = CocoDataset("/content/dataset_split/train/images", "/content/dataset_split/train/annotations.json")
val_ds = CocoDataset("/content/dataset_split/val/images", "/content/dataset_split/val/annotations.json")
test_ds = CocoDataset("/content/dataset_split/test/images", "/content/dataset_split/test/annotations.json")

train_dl = DataLoader(train_ds, batch_size=4, shuffle=True, collate_fn=collate_fn)
val_dl = DataLoader(val_ds, batch_size=4, shuffle=False, collate_fn=collate_fn)
test_dl = DataLoader(test_ds, batch_size=4, shuffle=False, collate_fn=collate_fn)

from torchvision.datasets import CocoDetection
from transformers import DetrImageProcessor

processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")

dataset = CocoDetection(
    "/content/dataset_split/train/images",
    "/content/dataset_split/train/annotations.json"
)

image, target = dataset[0]
image_id = dataset.ids[0]

encoding = processor(
    images=image,
    annotations={"image_id": image_id, "annotations": target},
    return_tensors="pt"
)

print("pixel_values :", encoding["pixel_values"].shape)
print("labels keys  :", encoding["labels"][0].keys())
print("bbox contoh  :", encoding["labels"][0]["boxes"])

"""**DETR LIGHTNING MODULE (TRAINING)**"""

class Detr(pl.LightningModule):
    def __init__(self, num_classes):
        super().__init__()
        self.model = DetrForObjectDetection.from_pretrained(
            CHECKPOINT,
            num_labels=num_classes,
            ignore_mismatched_sizes=True
        )

    def forward(self, pixel_values, pixel_mask):
        return self.model(pixel_values=pixel_values, pixel_mask=pixel_mask)

    def training_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("val_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        param_dicts = [
            {
                "params": [p for n, p in self.model.named_parameters() if "backbone" not in n and p.requires_grad]
            },
            {
                "params": [p for n, p in self.model.named_parameters() if "backbone" in n and p.requires_grad],
                "lr": 1e-5,
            },
        ]
        return torch.optim.AdamW(param_dicts, lr=1e-4, weight_decay=1e-4)

    def train_dataloader(self):
        return train_dl

    def val_dataloader(self):
        return val_dl

model = Detr(num_classes=len(train_ds.coco.cats))

trainer = pl.Trainer(
    accelerator="gpu",
    devices=1,
    max_epochs=300,
    gradient_clip_val=0.1,
    log_every_n_steps=10
)

trainer.fit(model)

import shutil

source_dir = "/content/lightning_logs/version_0"
zip_path = "/content/version_0.zip"

shutil.make_archive(
    base_name=zip_path.replace(".zip", ""),
    format="zip",
    root_dir=source_dir
)

print("ZIP selesai dibuat:", zip_path)

from google.colab import files
files.download("/content/version_0.zip")

import shutil

source_dir = "/content/dataset_split"
zip_path = "/content/dataset_split.zip"

shutil.make_archive(
    base_name=zip_path.replace(".zip", ""),
    format="zip",
    root_dir=source_dir
)

print("ZIP selesai dibuat:", zip_path)

from google.colab import files
files.download("/content/dataset_split.zip")

from google.colab import files

ckpt_path = "/content/drive/MyDrive/SKRIPSII/MODEL/epoch=299-step=37800.ckpt"

files.download(ckpt_path)

# download dataset
!zip -r /content/dataset.zip /content/dataset_split

"""**INFERENCE (WITH THRESHOLD)**"""

model.model.eval().to(DEVICE)

import cv2
import matplotlib.pyplot as plt

sample_img, _ = test_ds[0]

# convert tensor → numpy image
img = sample_img.permute(1, 2, 0).cpu().numpy()

plt.figure(figsize=(5,5))
plt.imshow(img)
plt.title("Sample Test Image")
plt.axis("off")
plt.show()

from PIL import Image
import os, torch

model.model.eval().to(DEVICE)

img_id = test_ds.ids[0]
img_info = test_ds.coco.loadImgs(img_id)[0]
img_path = os.path.join(test_ds.root, img_info["file_name"])

img = Image.open(img_path).convert("RGB")

inputs = processor(images=img, return_tensors="pt").to(DEVICE)

with torch.no_grad():
    outputs = model.model(**inputs)

print("Max logit confidence:",
      outputs.logits.softmax(-1).max().item())

results = processor.post_process_object_detection(
    outputs,
    threshold=0.5,
    target_sizes=torch.tensor([[img.height, img.width]]).to(DEVICE)
)[0]

print("=== DETR OUTPUT DEBUG ===")
print("Jumlah box   :", len(results["boxes"]))
print("Top 10 score :", results["scores"][:10])
print("Top 10 label :", results["labels"][:10])

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis("off")

for box, score in zip(results["boxes"], results["scores"]):
    if score < 0.2:
        continue

    x1, y1, x2, y2 = box.cpu().numpy()
    plt.gca().add_patch(
        plt.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            fill=False,
            edgecolor="red",
            linewidth=2
        )
    )
    plt.text(x1, y1, f"{score:.2f}", color="yellow")

plt.title("DETR Inference (Debug Mode)")
plt.show()



from PIL import Image
import os
import torch
import matplotlib.pyplot as plt
from transformers import DetrImageProcessor, DetrForObjectDetection
import pytorch_lightning as pl

# Define the image path provided by the user
img_path_user = "/content/dataset_split/test/images/58.jpg"

# --- BEGIN: Ensure DetrFineTune class and model_ft are available ---
# Assuming CHECKPOINT and DEVICE are already defined globally

# Re-define DetrFineTune class if not already in scope (or to make cell self-contained)
class DetrFineTune(pl.LightningModule):
    def __init__(self, num_classes):
        super().__init__()
        self.model = DetrForObjectDetection.from_pretrained(
            CHECKPOINT,
            num_labels=num_classes,
            ignore_mismatched_sizes=True
        )

    def forward(self, pixel_values, pixel_mask):
        return self.model(pixel_values=pixel_values, pixel_mask=pixel_mask)

    def training_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("val_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        param_dicts = [
            {
                "params": [p for n, p in self.model.named_parameters()
                           if "backbone" not in n and p.requires_grad],
            },
            {
                "params": [p for n, p in self.model.named_parameters()
                           if "backbone" in n and p.requires_grad],
                "lr": 1e-6,  # backbone lebih kecil
            },
        ]
        return torch.optim.AdamW(param_dicts, lr=1e-5, weight_decay=1e-4)

    def train_dataloader(self):
        return train_dl

    def val_dataloader(self):
        return val_dl

# Load the fine-tuned model from its checkpoint
# Assuming `train_ds` is available from previous data loading steps
# Use the last saved checkpoint path for fine-tuned model
CKPT_PATH_FINE_TUNE = "/content/drive/MyDrive/SKRIPSII/MODEL/epoch=299-step=37800.ckpt" # Updated path as per user request

# Check if model_ft is already defined to avoid re-loading if not necessary
if 'model_ft' not in locals() and 'model_ft' not in globals():
    model_ft = DetrFineTune.load_from_checkpoint(
        CKPT_PATH_FINE_TUNE,
        num_classes=len(train_ds.coco.cats)
    )

processor = DetrImageProcessor.from_pretrained(CHECKPOINT)
# --- END: Ensure DetrFineTune class and model_ft are available ---

# Load the image
img_user = Image.open(img_path_user).convert("RGB")

# Ensure the fine-tuned model is in evaluation mode and on the correct device
model_ft.model.eval()
model_ft.model.to(DEVICE)

# Process the image for the model
inputs_user = processor(
    images=img_user,
    return_tensors="pt"
).to(DEVICE)

# Perform inference
with torch.no_grad():
    outputs_user = model_ft.model(**inputs_user)

# Define target sizes for post-processing
target_sizes_user = torch.tensor([[img_user.height, img_user.width]]).to(DEVICE)

# Post-process the outputs with a threshold
# Using the threshold from the previous inference example (0.187)
results_user = processor.post_process_object_detection(
    outputs_user,
    threshold=0.05, # Adjusted threshold
    target_sizes=target_sizes_user
)[0]

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))
plt.imshow(img_user)
plt.axis("off")

# Plot bounding boxes for detected fractures
for box, score, label in zip(results_user["boxes"], results_user["scores"], results_user["labels"]):
    x1, y1, x2, y2 = box.cpu().numpy()
    plt.gca().add_patch(
        plt.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            fill=False,
            edgecolor="red",
            linewidth=2
        )
    )
    # Menghilangkan tulisan 'Fracture: score'
    # label_text = f"Fracture: {score:.2f}"
    # plt.text(x1, y1, label_text, color="yellow", fontsize=10, backgroundcolor='red')

plt.title(f"DETR – Fracture Detection for {os.path.basename(img_path_user)}")
plt.show()

"""**EVALUATION (COCO, NO THRESHOLD)**"""

from coco_eval import CocoEvaluator
from tqdm import tqdm
import torch

from pycocotools.coco import COCO

model.model.eval()
model.model.to(DEVICE)

# Create a COCO object for ground truth annotations using the annotation file path
coco_gt = COCO("/content/dataset_split/test/annotations.json")

evaluator = CocoEvaluator(
    coco_gt,
    iou_types=["bbox"]
)

for batch in tqdm(test_dl):
    with torch.no_grad():
        outputs = model.model(
            pixel_values=batch["pixel_values"].to(DEVICE),
            pixel_mask=batch["pixel_mask"].to(DEVICE)
        )

    # ukuran asli image (H, W)
    orig_sizes = torch.stack(
        [t["orig_size"] for t in batch["labels"]],
        dim=0
    )

    # POST-PROCESS TANPA THRESHOLD (PENTING)
    # FIX: Explicitly set threshold to a very low value to include all predictions for COCO evaluation
    results = processor.post_process_object_detection(
        outputs,
        threshold=0.001,  # Set threshold to a very small value to include all detections
        target_sizes=orig_sizes
    )

    all_predictions_for_batch = []
    for t, r in zip(batch["labels"], results):
        image_id = t["image_id"].item()
        # Ensure that 'boxes' tensor has elements before iterating
        if r["boxes"].numel() > 0:
            for box, score, label in zip(r["boxes"], r["scores"], r["labels"]):
                # Convert box from [x_min, y_min, x_max, y_max] to COCO format [x, y, width, height]
                x_min, y_min, x_max, y_max = box.tolist()
                bbox_coco_format = [x_min, y_min, x_max - x_min, y_max - y_min]
                all_predictions_for_batch.append({
                    'image_id': image_id,
                    'bbox': bbox_coco_format,
                    'score': score.item(),
                    'category_id': label.item(),
                })
    # Only update evaluator if there are any predictions to avoid potential internal errors
    if all_predictions_for_batch:
        evaluator.update(all_predictions_for_batch)

evaluator.synchronize_between_processes()
evaluator.accumulate()
evaluator.summarize()

"""**TEST CITRA FRAKTUR LAIN**"""

model = Detr.load_from_checkpoint(
    "/content/lightning_logs/version_0/checkpoints/epoch=299-step=75300.ckpt",
    num_classes=len(train_ds.coco.cats)
)

model.model.eval()
model.model.to(DEVICE)

from PIL import Image
import os

img_path = "/content/dataset_split/test/images/IMG0000804.jpg"
img = Image.open(img_path).convert("RGB")

inputs = processor(
    images=img,
    return_tensors="pt"
).to(DEVICE)

with torch.no_grad():
    outputs = model.model(**inputs)

target_sizes = torch.tensor([[img.height, img.width]]).to(DEVICE)

results = processor.post_process_object_detection(
    outputs,
    threshold=0.187,
    target_sizes=target_sizes
)[0]

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.imshow(img)
plt.axis("off")

for box, score in zip(results["boxes"], results["scores"]):
    x1, y1, x2, y2 = box.cpu().numpy()
    plt.gca().add_patch(
        plt.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            fill=False,
            edgecolor="red",
            linewidth=2
        )
    )
    plt.text(x1, y1, f"{score:.2f}", color="yellow")

plt.title("DETR – Fracture Detection (External Test)")
plt.show()

"""**UJI FINE-TUNING**"""

# FINE-TUNING FROM 300 EPOCH CKPT

CKPT_PATH = "/content/lightning_logs/version_0/checkpoints/epoch=299-step=75300.ckpt"

class DetrFineTune(pl.LightningModule):
    def __init__(self, num_classes):
        super().__init__()
        self.model = DetrForObjectDetection.from_pretrained(
            CHECKPOINT,
            num_labels=num_classes,
            ignore_mismatched_sizes=True
        )

    def forward(self, pixel_values, pixel_mask):
        return self.model(pixel_values=pixel_values, pixel_mask=pixel_mask)

    def training_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("train_loss", loss, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        labels = [{k: v.to(self.device) for k, v in t.items()} for t in batch["labels"]]
        outputs = self.model(
            pixel_values=batch["pixel_values"],
            pixel_mask=batch["pixel_mask"],
            labels=labels
        )
        loss = outputs.loss
        self.log("val_loss", loss, prog_bar=True)
        return loss

    def configure_optimizers(self):
        param_dicts = [
            {
                "params": [p for n, p in self.model.named_parameters()
                           if "backbone" not in n and p.requires_grad],
            },
            {
                "params": [p for n, p in self.model.named_parameters()
                           if "backbone" in n and p.requires_grad],
                "lr": 1e-6,  # backbone lebih kecil
            },
        ]
        return torch.optim.AdamW(param_dicts, lr=1e-5, weight_decay=1e-4)

    def train_dataloader(self):
        return train_dl

    def val_dataloader(self):
        return val_dl


# Init model
model_ft = DetrFineTune(num_classes=len(train_ds.coco.cats))

# Trainer untuk fine-tuning
trainer_ft = pl.Trainer(
    accelerator="gpu",
    devices=1,
    max_epochs=350,          # Changed from 50 to 350 (300 existing + 50 fine-tuning)
    gradient_clip_val=0.1,
    log_every_n_steps=10
)

# Resume training dari checkpoint 300 epoch
trainer_ft.fit(
    model_ft,
    ckpt_path=CKPT_PATH
)

# pakai model_ft untuk evaluasi
model_ft.model.eval().to(DEVICE)

from coco_eval import CocoEvaluator
from pycocotools.coco import COCO
from tqdm import tqdm
import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load ground truth COCO
coco_gt = COCO("/content/dataset_split/test/annotations.json")

evaluator = CocoEvaluator(
    coco_gt,
    iou_types=["bbox"]
)

model_ft.model.eval()
model_ft.model.to(DEVICE)

for batch in tqdm(test_dl):
    with torch.no_grad():
        outputs = model_ft.model(
            pixel_values=batch["pixel_values"].to(DEVICE),
            pixel_mask=batch["pixel_mask"].to(DEVICE)
        )

    # ambil ukuran asli image (H, W)
    orig_sizes = torch.stack(
        [t["orig_size"] for t in batch["labels"]],
        dim=0
    )

    # POST PROCESS TANPA THRESHOLD (WAJIB UNTUK COCO)
    results = processor.post_process_object_detection(
        outputs,
        threshold=0.001,  # sangat kecil supaya semua prediksi masuk
        target_sizes=orig_sizes.to(DEVICE)
    )

    all_predictions_for_batch = []

    for t, r in zip(batch["labels"], results):
        image_id = t["image_id"].item()

        if r["boxes"].numel() == 0:
            continue

        for box, score, label in zip(r["boxes"], r["scores"], r["labels"]):
            x_min, y_min, x_max, y_max = box.tolist()
            bbox_coco = [x_min, y_min, x_max - x_min, y_max - y_min]

            all_predictions_for_batch.append({
                "image_id": image_id,
                "bbox": bbox_coco,
                "score": score.item(),
                "category_id": label.item(),
            })

    if len(all_predictions_for_batch) > 0:
        evaluator.update(all_predictions_for_batch)

evaluator.synchronize_between_processes()
evaluator.accumulate()
evaluator.summarize()

from google.colab import files

ckpt_path = "/content/lightning_logs/version_2/checkpoints/epoch=349-step=87850.ckpt"

files.download(ckpt_path)

